In [1]:
import os

print(os.getcwd())

D:\Data-Analytics-Portfolio\02-Operations-Performance-Analytics\Python\Notebooks

In [2]:
!pip install pandas numpy sqlalchemy pymysql faker tqdm

Requirement already satisfied: pandas in c:\users\pc\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\pc\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: sqlalchemy in c:\users\pc\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\pc\anaconda3\lib\site-packages (1.2.0)
Collecting faker
  Downloading faker-40.36.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tqdm in c:\users\pc\anaconda3\lib\site-packages (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\pc\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pc\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: colorama in c:\users\pc\anaconda3\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\pc\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.36.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------------- ------------------- 1.0/2.1 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 5.6 MB/s  0:00:00
Installing collected packages: faker
Successfully installed faker-40.36.0

In [3]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from faker import Faker
from tqdm import tqdm

print("✅ All libraries imported successfully!")

✅ All libraries imported successfully!

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Sunny@123@localhost/operations_analytics"
)

print("Connected successfully!")

Connected successfully!

In [5]:
import pandas as pd

df = pd.read_sql("SELECT COUNT(*) AS Employees FROM dim_employee", engine)

df

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '123@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [6]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Sunny@123@localhost/operations_analytics"
)

print("✅ Connected to MySQL!")

✅ Connected to MySQL!

In [7]:
import pandas as pd

query = "SELECT COUNT(*) AS Employees FROM dim_employee"

df = pd.read_sql(query, engine)

df

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '123@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [8]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Sunny@123@127.0.0.1:3306/operations_analytics"
)

print("✅ Connected to MySQL!")

✅ Connected to MySQL!

In [9]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Sunny%40123@127.0.0.1:13306/operations_analytics"
)

print("✅ Connected to MySQL!")

✅ Connected to MySQL!

In [10]:
import pandas as pd

df = pd.read_sql(
    "SELECT COUNT(*) AS Employees FROM dim_employee",
    engine
)

df

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10061] No connection could be made because the target machine actively refused it)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [11]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Sunny%40123@127.0.0.1:3306/operations_analytics"
)

print("✅ Connected to MySQL!")

✅ Connected to MySQL!

In [12]:
import pandas as pd

df = pd.read_sql(
    "SELECT COUNT(*) AS Employees FROM dim_employee",
    engine
)

df

   Employees
0        500

In [13]:
dim_employee = pd.read_sql("SELECT * FROM dim_employee", engine)
dim_date = pd.read_sql("SELECT * FROM dim_date", engine)
dim_team = pd.read_sql("SELECT * FROM dim_team", engine)
dim_manager = pd.read_sql("SELECT * FROM dim_manager", engine)
dim_process = pd.read_sql("SELECT * FROM dim_process", engine)
dim_country = pd.read_sql("SELECT * FROM dim_country", engine)
dim_shift = pd.read_sql("SELECT * FROM dim_shift", engine)
dim_leave = pd.read_sql("SELECT * FROM dim_leave", engine)

print("Employees :", len(dim_employee))
print("Dates     :", len(dim_date))
print("Teams     :", len(dim_team))
print("Managers  :", len(dim_manager))
print("Processes :", len(dim_process))
print("Countries :", len(dim_country))
print("Shifts    :", len(dim_shift))
print("Leaves    :", len(dim_leave))

Employees : 500
Dates     : 365
Teams     : 6
Managers  : 6
Processes : 5
Countries : 5
Shifts    : 4
Leaves    : 8

In [14]:
import random
import numpy as np
from faker import Faker

fake = Faker()

# Number of records
NUM_RECORDS = 100000

print("Records to generate:", NUM_RECORDS)

Records to generate: 100000

In [15]:
employee_ids = dim_employee["employee_id"].tolist()
date_ids = dim_date["date_id"].tolist()
team_ids = dim_team["team_id"].tolist()
manager_ids = dim_manager["manager_id"].tolist()
process_ids = dim_process["process_id"].tolist()
country_ids = dim_country["country_id"].tolist()
shift_ids = dim_shift["shift_id"].tolist()
leave_ids = dim_leave["leave_id"].tolist()

print("Lookup lists ready!")

Lookup lists ready!

In [16]:
fact_data = []

attendance_options = ["Present", "WFH", "Leave"]

for i in range(NUM_RECORDS):

    employee = random.choice(employee_ids)
    date = random.choice(date_ids)

    team = random.choice(team_ids)
    manager = random.choice(manager_ids)
    process = random.choice(process_ids)
    country = random.choice(country_ids)
    shift = random.choice(shift_ids)

    attendance = random.choices(
        attendance_options,
        weights=[85, 10, 5],
        k=1
    )[0]

    if attendance == "Leave":
        leave = random.choice(leave_ids)
        login_hours = 0
        productive_hours = 0
        idle_hours = 0
        overtime_hours = 0
        cases_completed = 0
        cases_reopened = 0
        aht = 0
        quality = 0
        csat = 0
        adherence = 0
        escalation = 0

    else:

        leave = None

        login_hours = round(random.uniform(7.5,10.5),2)

        productive_hours = round(
            login_hours * random.uniform(0.70,0.90),2
        )

        idle_hours = round(
            login_hours - productive_hours,
            2
        )

        overtime_hours = round(
            max(0, login_hours-9),
            2
        )

        cases_completed = random.randint(35,110)

        cases_reopened = random.randint(0,5)

        aht = round(random.uniform(4,12),2)

        quality = round(random.uniform(85,100),2)

        csat = round(random.uniform(3.5,5),2)

        adherence = round(random.uniform(85,100),2)

        escalation = random.randint(0,3)

    fact_data.append([

        date,
        employee,
        team,
        manager,
        process,
        country,
        shift,
        leave,

        login_hours,
        productive_hours,
        idle_hours,
        overtime_hours,

        cases_completed,
        cases_reopened,
        aht,
        quality,
        csat,
        adherence,
        attendance,
        escalation

    ])

print("Fact rows generated:", len(fact_data))

Fact rows generated: 100000

In [17]:
fact_df = pd.DataFrame(
    fact_data,
    columns=[
        "date_id",
        "employee_id",
        "team_id",
        "manager_id",
        "process_id",
        "country_id",
        "shift_id",
        "leave_id",
        "login_hours",
        "productive_hours",
        "idle_hours",
        "overtime_hours",
        "cases_completed",
        "cases_reopened",
        "average_handle_time",
        "quality_score",
        "csat_score",
        "adherence_percent",
        "attendance_status",
        "escalation_count"
    ]
)

fact_df.head()

,date_id,employee_id,team_id,manager_id,process_id,country_id,shift_id,leave_id,login_hours,productive_hours,idle_hours,overtime_hours,cases_completed,cases_reopened,average_handle_time,quality_score,csat_score,adherence_percent,attendance_status,escalation_count
0,20251128,E0125,T006,M006,P003,C005,S002,None,7.62,6.32,1.30,0.00,54,3,5.53,95.30,4.41,86.42,Present,1
1,20250909,E0262,T003,M002,P001,C004,S001,None,9.58,8.11,1.47,0.58,74,3,9.98,98.63,4.29,88.68,Present,2
2,20250330,E0102,T005,M005,P004,C002,S001,None,8.69,6.30,2.39,0.00,78,2,5.33,95.16,4.20,92.03,Present,0
3,20250208,E0289,T002,M006,P001,C001,S001,None,8.15,6.05,2.10,0.00,82,3,5.01,85.81,4.07,90.92,Present,3
4,20251022,E0152,T003,M003,P003,C003,S001,L006,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,Leave,0

In [19]:
output_path = r"D:\Data-Analytics-Portfolio\02-Operations-Performance-Analytics\Dataset\Fact_Data\fact_operations.csv"

fact_df.to_csv(output_path, index=False)

print("✅ File exported successfully!")
print(output_path)

✅ File exported successfully!
D:\Data-Analytics-Portfolio\02-Operations-Performance-Analytics\Dataset\Fact_Data\fact_operations.csv

In [20]:
from sqlalchemy import text

# Optional: make sure the table is empty before inserting
with engine.begin() as conn:
    conn.execute(text("DELETE FROM fact_operations"))

print("✅ fact_operations table cleared.")

✅ fact_operations table cleared.

In [21]:
fact_df.to_sql(
    name="fact_operations",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=5000,
    method="multi"
)

print("✅ 100000 rows inserted successfully!")

✅ 100000 rows inserted successfully!